project:
  type: website
  output-dir: docs

website:
  title: "Kinda Kinksy"
  twitter-card: true
#  page-navigation: true   # doesn't work without sidebar
  navbar:
    logo: "img/kinks.png"
    left:
      - href: index.qmd
        text: Home
      - href: setlist.qmd
        text: Setlist
      - contact.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/jtkulas/kindakinksy
          - text: Report an Issue
            href: https://github.com/jtkulas/kindakinksy/issues
      - icon: facebook
        href: https://facebook.com
      - icon: instagram
        href: https://instagram.com
      - icon: twitter-x
        href: https://x.com
  page-footer:  
    border: true
    left: "©Kinda Kinksy 2026"
    right: 
      - text: "Contact Us"
        href: contact.qmd
    
format:
  html:
#    mainfont: Oswald
    theme:
      light: lumen
      dark: darkly
    css: styles.css
    toc: true